spring:
  application:
    name:  vbuynet-service-sso
  datasource:
    druid:
      url: jdbc:mysql://192.168.43.220:3306/sl?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.43.70:6379
  cloud:
    nacos:
      discovery:
        server-addr: 169.254.205.148:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 169.254.205.148:8848

server:
  port: 9501

mybatis:
  type-aliases-package: com.ls.vbuynet.commons.domain
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
