spring:
  application:
    name: Vbuynet-service-provider-comments
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.253.1:8848

server:
  port: 8504

management:
  endpoints:
    web:
      exposure:
        include: "*"