spring:
  application:
    name: Vbuynet-service-provider-comments
  cloud:
    nacos:
      discovery:
        server-addr: 169.254.205.148:8848/nacos
    sentinel:
      transport:
        port: 8719
        dashboard: 169.254.205.148:8848

server:
  port: 8504

management:
  endpoints:
    web:
      exposure:
        include: "*"